
<?php
/**
 * @file
 * Code for the news feature.
 */

include_once 'news_feature.features.inc';

/**
 * Implements hook_integration().
 */
function news_feature_integration() {
  // Add links to views if a module wants to do that.
  return array(
    'news_feature' => array(
      'entity' => array(
        'node'=> array(
          'news' => array(
            'add_content_link' => TRUE,
            'image'=> array(
              'enabled' => TRUE,
            ),
          ),
        ),
      ),
      'views' => array(
        'news' => array(
          'block' => array(
            'add_content_link' => array(
              'areas' => array('footer'),
            ),
          ),
        ),
        'news_list' => array(
          'block' => array(
            'add_content_link' => array(
              'areas' => array('footer'),
            ),
          ),
        ),
      ),
    ),
  );
}
